CREATE DATABASE IF NOT EXISTS slider_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE slider_app;

CREATE TABLE IF NOT EXISTS slides (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tab_name VARCHAR(100) NOT NULL,
  slide_title VARCHAR(255) DEFAULT NULL,
  slide_description TEXT DEFAULT NULL,
  image_path VARCHAR(255) NOT NULL,
  slide_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
